# Generated by Django 3.2.3 on 2021-08-14 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('work_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('progress_rate', models.FloatField(blank=True, null=True, verbose_name='進捗率')),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='期間')),
                ('planed_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='予定工数')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='実績工数')),
                ('planned_start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='予定開始日時')),
                ('planned_end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='予定終了日時')),
                ('actual_start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='実績開始日時')),
                ('actual_end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='実績終了日時')),
                ('memo', models.TextField(blank=True, max_length=50, verbose_name='備考')),
                ('is_milestone', models.BooleanField(default=False, verbose_name='マイルストーン')),
                ('picture', models.FileField(blank=True, upload_to='student/')),
                ('task_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskline.taskcategory')),
                ('task_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, max_length=50, verbose_name='備考')),
                ('tags', models.ManyToManyField(blank=True, to='taskline.ProjectTag')),
            ],
        ),
    ]
