# Generated by Django 3.2.3 on 2021-07-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='実績終了日時'),
        ),
        migrations.AddField(
            model_name='task',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='実績工数'),
        ),
        migrations.AddField(
            model_name='task',
            name='actual_start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='実績開始日時'),
        ),
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='期間'),
        ),
        migrations.AddField(
            model_name='task',
            name='planed_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='予定工数'),
        ),
        migrations.AddField(
            model_name='task',
            name='planned_end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='予定終了日時'),
        ),
        migrations.AddField(
            model_name='task',
            name='planned_start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='予定開始日時'),
        ),
        migrations.AddField(
            model_name='task',
            name='progress_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='進捗率'),
        ),
        migrations.AlterField(
            model_name='task',
            name='work_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
