# Generated by Django 3.2.3 on 2021-07-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskline', '0002_auto_20210723_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='memo',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
