# Generated by Django 3.2.3 on 2021-07-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskline', '0004_task_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='is_milestone',
            field=models.BooleanField(default=False, verbose_name='マイルストーン'),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='期間'),
        ),
        migrations.AlterField(
            model_name='task',
            name='memo',
            field=models.TextField(blank=True, max_length=50, verbose_name='備考'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, max_length=50, verbose_name='備考')),
                ('tags', models.ManyToManyField(blank=True, to='taskline.ProjectTag')),
            ],
        ),
    ]
