# Generated by Django 3.2.3 on 2021-07-08 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'permissions': [('superman', 'aaaa'), ('batman', 'bbbb')]},
        ),
    ]
